"""init Frameworks table

Revision ID: 000144ee09f8
Revises: 9bc2f54bdd38
Create Date: 2025-04-27 23:29:39.129832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000144ee09f8'
down_revision: Union[str, None] = '9bc2f54bdd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entries', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_deleted_at'), 'frameworks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_frameworks_id'), 'frameworks', ['id'], unique=False)
    op.create_index(op.f('ix_frameworks_is_deleted'), 'frameworks', ['is_deleted'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_frameworks_is_deleted'), table_name='frameworks')
    op.drop_index(op.f('ix_frameworks_id'), table_name='frameworks')
    op.drop_index(op.f('ix_frameworks_deleted_at'), table_name='frameworks')
    op.drop_table('frameworks')
    # ### end Alembic commands ###
